name: Compile and Sync Content

on:
  push:
    branches:
      - content

permissions:
  contents: write
  pull-requests: write

jobs:
  process-and-sync:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 2: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          pip install pandas openpyxl

      # Step 5: Run the Python script
      - name: Run compile_content.py
        run: |
          python .github/script/compile_content.py --dataset .github/datasets/dataset.xlsx

      # Step 6: Commit report.md to content branch
      - name: Commit report.md to content branch
        run: |
          git add report.md
          git commit -m "Update report.md"
          git push origin content

      # Step 7: Handle build directory before switching branches
      - name: Move untracked build files temporarily
        run: |
          mkdir -p ../temp_build
          cp -r build/* ../temp_build/
          git clean -fd # Removes untracked files

      # Step 8: Switch to staging branch
      - name: Switch to staging branch
        run: |
          git fetch origin
          git checkout -B staging origin/staging

      # Step 9: Restore build files to staging branch
      - name: Restore build files to staging branch
        run: |
          cp -r ../temp_build/* build/
          rm -rf ../temp_build # Clean up the temporary folder
          git add build/
          git commit -m "Sync compiled files to staging"
          git push origin staging

      # Step 10: Create Pull Request to main
      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update compiled markdown files and report"
          title: "Update main with changes from staging"
          body: "This PR includes updates from the staging branch."
          branch: "staging-content-update"
          base: "main"
          labels: |
            automated-pr
            content-update
