name: Compile and Sync Content

on:
  push:
    branches:
      - content

permissions:
  contents: write
  pull-requests: write

jobs:
  process-and-sync:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 2: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          pip install pandas openpyxl

      # Step 5: Run the Python script
      - name: Run compile_content.py
        run: |
          python .github/script/compile_content.py --dataset .github/datasets/dataset.xlsx

      # Step 6: Move build folder to root
      - name: Move build folder to root
        run: |
          mkdir -p ../build && cp -r build/* ../build/

      - name: Copy report.md to root
        run: |
          cp report.md ../

      # Step 7: Commit report.md to content branch
      - name: Commit report.md to content branch
        run: |
          git add report.md
          git commit -m "Update report.md"
          git push origin content

      # Step 7: Switch to staging branch
      - name: Switch to staging branch
        run: |
          git fetch origin
          git checkout staging

      # Step 8: Sync compiled files and report.md to staging
      - name: Commit compiled files and report.md to staging
        run: |
          git rm -rf build/ || true                    # Remove existing build folder from repo
          cp -r ../build/ build/                       # Bring only the new compiled files back
          git add build/
          cp ../report.md report.md
          git add report.md
          git commit -m "Sync compiled files and report.md to staging"
          git push origin staging

      # Step 9: Create Pull Request to main
      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update compiled markdown files and report"
          title: "Update main with changes from staging"
          body: "This PR includes updates from the staging branch."
          branch: "staging-content-update"
          base: "main"
          labels: |
            automated-pr
            content-update
