name: PR Validation Workflow

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - content

jobs:
  validate-markdown:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Checkout head branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}  # Ensure the base branch is checked out

      - name: Log current branch
        run: |
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"

      - name: Print files in content folder
        run: |
          echo "Listing all files in the content folder of the base branch:"
            ls -R content/

