name: PR Validation Workflow

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - content

jobs:
  validate-markdown:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 2: Checkout the base branch (content)
      - name: Checkout the base branch (content)
        uses: actions/checkout@v3
        with:
          ref: content  # Checkout the base branch (content)

      # Step 3: Fetch the head branch (pull request)
      - name: Checkout the pull request branch (HEAD)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}  # Checkout the pull request branch

      # Step 4: Get the list of changed files between the base and head branches
      - name: Get list of changed or added files
        run: |
          # Compare the base (content) branch with the pull request branch (HEAD)
          CHANGED_FILES=$(git diff --name-only --diff-filter=AM content..${{ github.event.pull_request.head.ref }})

          # Output the list of changed or added files
          echo "Changed or created files in the pull request:"
          echo "$CHANGED_FILES"
