name: PR Validation Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - content

jobs:
  validate-markdown:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the base branch (content)
      - name: Checkout the base branch (content)
        uses: actions/checkout@v3
        with:
          ref: content  # Checkout the base branch (content)

      # Step 2: Fetch the pull request branch (HEAD)
      - name: Fetch the pull request branch (HEAD)
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}

      # Step 3: Checkout the pull request branch (HEAD)
      - name: Checkout the pull request branch (HEAD)
        run: |
          git checkout ${{ github.event.pull_request.head.ref }}

      # Step 4: Merge the base (content) branch into the pull request branch (HEAD)
      - name: Merge content into HEAD
        run: |
          git merge origin/content --no-ff --no-commit  # Merge the base branch into the HEAD branch without committing yet

      # Step 5: Get the list of changed or added files
      - name: Get list of new or changed files after the merge
        run: |
          # Get the list of files that have been changed or added since the last sync (after the merge)
          CHANGED_FILES=$(git diff --name-only --diff-filter=AM origin/content...HEAD)

          # Output the list of changed or added files
          echo "Changed or created files in the pull request after the merge:"
          echo "$CHANGED_FILES"
