name: PR Validation Workflow

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - content

jobs:
  validate-markdown:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 2: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          pip install pandas openpyxl

      - name: Identify changed markdown files
        run: |
          BASE_SHA=${{ github.event.pull_request.base.sha || 'HEAD^' }}
          HEAD_SHA=${{ github.event.pull_request.head.sha || 'HEAD' }}
          CHANGED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep '^content/' || true)
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "Changed Markdown files: $CHANGED_FILES"

